#!/usr/bin/env python3
# Regenerates modules/box/src/syscalls.inc from the Linux UAPI headers installed on the build host
# (linux-libc-dev). Run it by hand when newer headers are available; the output is committed so the
# build does not depend on the host's header version.
#
#   python3 modules/box/tools/gen_syscalls.py > modules/box/src/syscalls.inc
import re
import subprocess
import sys

# Syscalls newer than the headers this was first generated with. Since 4.20/5.1 every architecture
# shares one number for each new syscall (x32 adds its 0x40000000 bit), so one list covers them all.
EXTRA_COMMON = {
    "mseal": 462, "setxattrat": 463, "getxattrat": 464, "listxattrat": 465, "removexattrat": 466,
    "open_tree_attr": 467, "file_getattr": 468, "file_setattr": 469,
}

X32_BIT = 0x40000000


def macros(header, defines=()):
    args = ["gcc", "-E", "-dM", "-x", "c", "-"]
    for d in defines:
        args.append("-D" + d)
    src = "#include <%s>\n" % header
    out = subprocess.run(args, input=src.encode(), capture_output=True, check=True).stdout.decode()
    table = {}
    for line in out.splitlines():
        m = re.match(r"#define (\w+) (.*)$", line)
        if m:
            table[m.group(1)] = m.group(2).strip()
    return table


def evaluate(table, value, depth=0):
    if depth > 16:
        raise ValueError(value)

    def repl(m):
        word = m.group(0)
        if word in table:
            return "(" + str(evaluate(table, table[word], depth + 1)) + ")"
        return word

    expr = re.sub(r"[A-Za-z_]\w*", repl, value)
    return int(eval(expr))


def collect(header, defines=(), extra_bit=0):
    table = macros(header, defines)
    result = {}
    for key, value in table.items():
        if not key.startswith("__NR_") or key.startswith("__NR3264_") or key == "__NR_syscalls":
            continue
        try:
            nr = evaluate(table, value)
        except Exception:
            continue
        result[key[5:]] = nr
    for name, nr in EXTRA_COMMON.items():
        result.setdefault(name, nr | extra_bit)
    return result


def emit(name, table):
    print("static const SyscallEntry %s[] = {" % name)
    for sys_name, nr in sorted(table.items()):
        print('    { "%s", %d },' % (sys_name, nr))
    print("};")
    print()


def main():
    x86_64 = collect("asm/unistd_64.h")
    i386 = collect("asm/unistd_32.h")
    x32 = collect("asm/unistd_x32.h", ("__X32_SYSCALL_BIT=0x40000000",), extra_bit=X32_BIT)
    aarch64 = collect("asm-generic/unistd.h", ("__BITS_PER_LONG=64", "__ARCH_WANT_RENAMEAT", "__ARCH_WANT_NEW_STAT",
                                               "__ARCH_WANT_SET_GET_RLIMIT", "__ARCH_WANT_TIME32_SYSCALLS",
                                               "__ARCH_WANT_SYS_CLONE3", "__ARCH_WANT_MEMFD_SECRET"))
    print("// Generated by modules/box/tools/gen_syscalls.py from the Linux UAPI headers. Do not edit.")
    print()
    emit("SYSCALLS_X86_64", x86_64)
    emit("SYSCALLS_X86", i386)
    emit("SYSCALLS_X32", x32)
    emit("SYSCALLS_AARCH64", aarch64)


if __name__ == "__main__":
    sys.exit(main())
