#!/usr/bin/env python3
# Regenerates the embedded test vectors of the archive module:
#   deflate_vectors.hpp (python zlib/gzip), zstd_vectors.hpp (python-zstandard), tar_vectors.hpp
#   (python tarfile).
# The payloads come from the same deterministic generators as testdata.hpp, so the C++ tests can
# rebuild the expected plaintext instead of embedding it.
#
# Usage: PYTHONPATH=<dir with zstandard> python3 gen_fixtures.py
import base64
import gzip
import io
import os
import struct
import tarfile
import zlib

import zstandard

HERE = os.path.dirname(os.path.abspath(__file__))
WORDS = ["the", "quick", "brown", "fox", "jumps", "over", "lazy", "dog", "lorem", "ipsum",
         "dolor", "sit", "amet", "sbox", "layer", "tar", "\n"]


class Rng:
    def __init__(self, seed):
        self.x = seed or 1

    def next(self):
        x = self.x
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= x >> 17
        x ^= (x << 5) & 0xFFFFFFFF
        self.x = x & 0xFFFFFFFF
        return self.x


def random_bytes(n, seed):
    r = Rng(seed)
    return bytes((r.next() >> 24) for _ in range(n))


def text(n, seed):
    r = Rng(seed)
    out = bytearray()
    while len(out) < n:
        out += WORDS[r.next() % 17].encode() + b" "
    return bytes(out[:n])


def repeat(n, period, seed):
    unit = text(period, seed)
    return (unit * (n // period + 1))[:n]


# A payload description understood by the C++ side: list of (kind, n, seed, period).
# kind 0 random, 1 text, 2 repeat, 3 zeros.
def build(parts):
    out = b""
    for kind, n, seed, period in parts:
        if kind == 0:
            out += random_bytes(n, seed)
        elif kind == 1:
            out += text(n, seed)
        elif kind == 2:
            out += repeat(n, period, seed)
        else:
            out += bytes(n)
    return out


def c_bytes(data):
    lines = []
    for i in range(0, len(data), 24):
        lines.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 24]) + ",")
    return "\n".join(lines) if lines else "    0x00,"


def emit(path, guard, vectors):
    out = ["// Generated by gen_fixtures.py -- do not edit.", "#ifndef " + guard, "#define " + guard, "",
           "#include <cstddef>", "#include <cstdint>", "", "namespace fixtures {", ""]
    names = []
    for name, data, parts, extra in vectors:
        out.append("static const uint8_t %s_data[] = {" % name)
        out.append(c_bytes(data))
        out.append("};")
        out.append("")
        names.append((name, len(data), parts, extra))

    out.append("struct SPart { int kind; size_t n; uint32_t seed; size_t period; };")
    out.append("struct SVector { const char* name; const uint8_t* data; size_t size; int format; "
               "int parts; SPart part[3]; };")
    out.append("")
    out.append("static const SVector %s_list[] = {" % guard.lower().strip("_"))
    for name, size, parts, extra in names:
        ps = ", ".join("{ %d, %d, %d, %d }" % p for p in parts)
        out.append("    { \"%s\", %s_data, %d, %d, %d, { %s } }," % (name, name, size, extra, len(parts), ps))
    out.append("};")
    out.append("")
    out.append("}")
    out.append("")
    out.append("#endif")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")


def raw_deflate(data, level=6, strategy=zlib.Z_DEFAULT_STRATEGY, wbits=-15, memlevel=8, flush_every=0):
    c = zlib.compressobj(level, zlib.DEFLATED, wbits, memlevel, strategy)
    out = b""
    if flush_every:
        for i in range(0, len(data), flush_every):
            out += c.compress(data[i:i + flush_every])
            out += c.flush(zlib.Z_SYNC_FLUSH if (i // flush_every) % 2 == 0 else zlib.Z_FULL_FLUSH)
    else:
        out += c.compress(data)
    out += c.flush()
    return out


def gzip_with_all_fields(data):
    body = raw_deflate(data, 9)
    flags = 0x02 | 0x04 | 0x08 | 0x10
    hdr = b"\x1f\x8b\x08" + bytes([flags]) + struct.pack("<I", 1700000000) + b"\x02\x03"
    hdr += struct.pack("<H", 6) + b"AB\x02\x00xy"
    hdr += b"hello.txt\x00" + b"a comment\x00"
    hdr += struct.pack("<H", zlib.crc32(hdr) & 0xFFFF)
    return hdr + body + struct.pack("<II", zlib.crc32(data), len(data) & 0xFFFFFFFF)


# Formats: 0 raw, 1 zlib, 2 gzip.
def deflate_vectors():
    v = []
    t20 = [(1, 20000, 11, 0)]
    for lvl in (0, 1, 6, 9):
        v.append(("zlib_text_l%d" % lvl, zlib.compress(build(t20), lvl), t20, 1))
    t5 = [(1, 5000, 12, 0)]
    for sname, strat in (("fixed", zlib.Z_FIXED), ("huffonly", zlib.Z_HUFFMAN_ONLY), ("rle", zlib.Z_RLE),
                         ("filtered", zlib.Z_FILTERED)):
        v.append(("raw_%s" % sname, raw_deflate(build(t5), 6, strat), t5, 0))
    v.append(("raw_wbits9", raw_deflate(build(t5), 9, wbits=-9, memlevel=1), t5, 0))
    v.append(("raw_flushes", raw_deflate(build(t5), 6, flush_every=700), t5, 0))
    r5 = [(0, 5000, 13, 0)]
    v.append(("zlib_random", zlib.compress(build(r5), 6), r5, 1))
    rep = [(2, 400000, 14, 3000)]
    v.append(("gzip_repeat", gzip.compress(build(rep), 9, mtime=0), rep, 2))
    z = [(3, 100000, 0, 0)]
    v.append(("gzip_zeros", gzip.compress(build(z), 6, mtime=0), z, 2))
    e = []
    v.append(("gzip_empty", gzip.compress(b"", 6, mtime=0), e, 2))
    v.append(("zlib_empty", zlib.compress(b"", 6), e, 1))
    a = [(1, 1000, 15, 0)]
    b = [(1, 2000, 16, 0)]
    v.append(("gzip_multi", gzip.compress(build(a), 6, mtime=0) + gzip.compress(build(b), 1, mtime=0), a + b, 2))
    v.append(("gzip_fields", gzip_with_all_fields(build(t5)), t5, 2))
    return v


def zstd_vectors():
    v = []
    t = [(1, 50000, 21, 0)]
    data = build(t)
    for lvl in (1, 3, 9, 19):
        c = zstandard.ZstdCompressor(level=lvl, write_checksum=True)
        v.append(("zstd_text_l%d" % lvl, c.compress(data), t, 0))
    params = zstandard.ZstdCompressionParameters.from_level(22, window_log=17, write_checksum=1)
    c = zstandard.ZstdCompressor(compression_params=params)
    v.append(("zstd_text_l22", c.compress(data), t, 0))

    big = [(1, 262144, 22, 0)]
    c = zstandard.ZstdCompressor(level=19, write_checksum=True)
    v.append(("zstd_text_multiblock", c.compress(build(big)), big, 0))

    c = zstandard.ZstdCompressor(level=3, write_checksum=False, write_content_size=False)
    o = c.compressobj()
    v.append(("zstd_nosize", o.compress(data) + o.flush(), t, 0))

    r = [(0, 3000, 23, 0)]
    c = zstandard.ZstdCompressor(level=3, write_checksum=True)
    v.append(("zstd_random", c.compress(build(r)), r, 0))

    z = [(3, 300000, 0, 0)]
    v.append(("zstd_zeros", c.compress(build(z)), z, 0))

    rep = [(2, 4 << 20, 24, 3000)]
    params = zstandard.ZstdCompressionParameters.from_level(3, window_log=20, write_checksum=1)
    c2 = zstandard.ZstdCompressor(compression_params=params)
    v.append(("zstd_repeat_wrap", c2.compress(build(rep)), rep, 0))

    small = [(1, 20000, 25, 0)]
    params = zstandard.ZstdCompressionParameters.from_level(9, window_log=10, write_checksum=1, write_content_size=0)
    c3 = zstandard.ZstdCompressor(compression_params=params)
    o = c3.compressobj()
    v.append(("zstd_window1k", o.compress(build(small)) + o.flush(), small, 0))

    a = [(1, 7000, 26, 0)]
    b = [(0, 500, 27, 0)]
    skippable = struct.pack("<II", 0x184D2A53, 5) + b"skip!"
    c = zstandard.ZstdCompressor(level=5, write_checksum=True)
    v.append(("zstd_multiframe", c.compress(build(a)) + skippable + c.compress(build(b)), a + b, 0))

    # --> Matches 16 MiB back: needs a 32 MiB window (format 1 marks "window > 8 MiB").
    far = [(0, 1000, 28, 0), (3, 16 << 20, 0, 0), (0, 1000, 28, 0)]
    params = zstandard.ZstdCompressionParameters.from_level(19, window_log=25, enable_ldm=1, write_checksum=1, write_content_size=0)
    c4 = zstandard.ZstdCompressor(compression_params=params)
    o = c4.compressobj()
    v.append(("zstd_long_window", o.compress(build(far)) + o.flush(), far, 1))
    return v


def tar_vectors():
    v = []

    def add(tf, name, data=b"", **kw):
        ti = tarfile.TarInfo(name)
        for k, val in kw.items():
            setattr(ti, k, val)
        ti.size = len(data) if ti.type in (tarfile.REGTYPE, tarfile.AREGTYPE) else 0
        tf.addfile(ti, io.BytesIO(data) if ti.size else None)

    long_dir = "d" * 60 + "/" + "e" * 60 + "/"
    long_name = long_dir + "f" * 80
    long_link = "/target/" + "t" * 120

    for fmt_name, fmt in (("gnu", tarfile.GNU_FORMAT), ("pax", tarfile.PAX_FORMAT), ("ustar", tarfile.USTAR_FORMAT)):
        buf = io.BytesIO()
        gh = {"comment": "global"} if fmt == tarfile.PAX_FORMAT else None
        tf = tarfile.open(fileobj=buf, mode="w", format=fmt, pax_headers=gh)
        add(tf, "dir/", type=tarfile.DIRTYPE, mode=0o755, mtime=1600000000, uid=1, gid=2, uname="u1", gname="g1")
        add(tf, "dir/file.txt", b"hello world\n", mode=0o644, mtime=1600000001, uid=1000, gid=1000,
            uname="alice", gname="staff")
        if fmt != tarfile.USTAR_FORMAT:
            add(tf, long_name, b"long name\n", mode=0o600, mtime=1600000002)
            add(tf, "dir/longlink", type=tarfile.SYMTYPE, linkname=long_link, mode=0o777, mtime=1600000003)
        else:
            # --> ustar splits a long path into prefix + name.
            add(tf, long_dir + "f" * 40, b"prefix split\n", mode=0o600, mtime=1600000002)
        add(tf, "dir/sym", type=tarfile.SYMTYPE, linkname="file.txt", mode=0o777, mtime=1600000004)
        add(tf, "dir/hard", type=tarfile.LNKTYPE, linkname="dir/file.txt", mode=0o644, mtime=1600000005)
        add(tf, "dir/fifo", type=tarfile.FIFOTYPE, mode=0o600, mtime=1600000006)
        add(tf, "dir/chr", type=tarfile.CHRTYPE, devmajor=1, devminor=3, mode=0o666, mtime=1600000007)
        add(tf, "dir/blk", type=tarfile.BLKTYPE, devmajor=7, devminor=0, mode=0o660, mtime=1600000008)
        if fmt == tarfile.GNU_FORMAT:
            # --> uid above 8^7 - 1 forces base-256 in GNU format.
            add(tf, "dir/bigid", b"x", mode=0o644, uid=1 << 30, gid=(1 << 21) + 5, mtime=1600000009)
        if fmt == tarfile.PAX_FORMAT:
            ti = tarfile.TarInfo("dir/xattr")
            ti.size = 3
            ti.mtime = 1600000010.25
            ti.uid = 1 << 30
            ti.uname = "u" * 40
            ti.pax_headers = {
                "SCHILY.xattr.user.foo": "bar",
                "SCHILY.xattr.security.capability": "\x01\x00\x00\x02",
                "LIBARCHIVE.xattr.user.lib%20x": base64.b64encode(b"libval").decode().rstrip("="),
                "mtime": "1600000010.25",
            }
            tf.addfile(ti, io.BytesIO(b"abc"))
        tf.close()
        v.append(("tar_%s" % fmt_name, buf.getvalue(), [], 0))
    return v


def main():
    emit(os.path.join(HERE, "deflate_vectors.hpp"), "__FIXTURES_DEFLATE_VECTORS_HPP__", deflate_vectors())
    emit(os.path.join(HERE, "zstd_vectors.hpp"), "__FIXTURES_ZSTD_VECTORS_HPP__", zstd_vectors())
    emit(os.path.join(HERE, "tar_vectors.hpp"), "__FIXTURES_TAR_VECTORS_HPP__", tar_vectors())


if __name__ == "__main__":
    main()
