#include <sbox/vpn/l2tp/profiles.hpp>
#include <sbox/vpn/ipsec/ikecrypto.hpp>
#include <certpp/string.hpp>
#include <certpp/utils/base64.hpp>
#include <cstdio>

namespace sbox {
namespace vpn {

    namespace {

        /* Base64 of bytes. */
        std::string base64(std::string_view data) {
            certpp::CString out;
            if (!certpp::CBase64::encode(out, certpp::SReadOnlyByteSpan(reinterpret_cast<const uint8_t*>(data.data()), data.size()), false)) {
                return std::string();
            }

            return std::string(out.toPtr(), out.size());
        }

        /* Escapes XML text. */
        std::string xml(std::string_view text) {
            std::string out;
            for (char c : text) {
                switch (c) {
                case '&': out += "&amp;"; break;
                case '<': out += "&lt;"; break;
                case '>': out += "&gt;"; break;
                case '"': out += "&quot;"; break;
                case '\'': out += "&apos;"; break;
                default: out += c; break;
                }
            }

            return out;
        }

        /* PowerShell single-quoted string. */
        std::string ps(std::string_view text) {
            std::string out = "'";
            for (char c : text) {
                out += c == '\'' ? std::string("''") : std::string(1, c);
            }

            return out + "'";
        }

        /* Random version 4 UUID. */
        std::string uuid() {
            uint8_t b[16];
            IkeRandom(SByteSpan(b, sizeof(b)));
            b[6] = uint8_t((b[6] & 0x0f) | 0x40);
            b[8] = uint8_t((b[8] & 0x3f) | 0x80);
            char out[40];
            std::snprintf(out, sizeof(out), "%02X%02X%02X%02X-%02X%02X-%02X%02X-%02X%02X-%02X%02X%02X%02X%02X%02X", b[0], b[1], b[2], b[3],
                          b[4], b[5], b[6], b[7], b[8], b[9], b[10], b[11], b[12], b[13], b[14], b[15]);
            return out;
        }

        /* Reverse-DNS fragment. */
        std::string ident(std::string_view text) {
            std::string out;
            for (char c : text) {
                bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9');
                out += ok ? c : '-';
            }

            return out.empty() ? std::string("vpn") : out;
        }

        /* Windows -AuthenticationMethod value. */
        const char* windowsAuth(EPppAuth a) {
            switch (a) {
            case EPPPA_PAP: return "Pap";
            case EPPPA_CHAP_MD5: return "Chap";
            default: return "MSChapv2";
            }
        }

    }

    /* Windows script. */
    std::string WindowsL2tpSetup(const SL2tpClientProfile& p) {
        std::string s;
        s += "# L2TP/IPsec (pre-shared key) connection for Windows 10/11 -- run in an elevated PowerShell.\n";
        s += "# Generated by libsbox. IPsec protects the tunnel, so no MPPE is negotiated ('Required' refers to IPsec).\n";
        if (p.serverBehindNat) {
            s += "\n# The server sits behind NAT: allow UDP-encapsulated ESP towards it, then REBOOT once.\n";
            s += "New-ItemProperty -Path 'HKLM:\\SYSTEM\\CurrentControlSet\\Services\\PolicyAgent' `\n";
            s += "    -Name AssumeUDPEncapsulationContextOnSendRule -PropertyType DWord -Value 2 -Force | Out-Null\n";
        }

        s += "\nAdd-VpnConnection -Name " + ps(p.name) + " -ServerAddress " + ps(p.server) + " -TunnelType L2tp `\n";
        s += "    -L2tpPsk " + ps(p.psk) + " -AuthenticationMethod " + windowsAuth(p.auth) + " -EncryptionLevel Required `\n";
        s += "    -RememberCredential -Force" + std::string(p.routes.empty() ? "" : " -SplitTunneling") + "\n";
        for (const std::string& r : p.routes) {
            s += "Add-VpnConnectionRoute -ConnectionName " + ps(p.name) + " -DestinationPrefix " + ps(r) + "\n";
        }

        s += "\n# Connect (or use the network flyout):\n";
        s += "# rasdial " + ps(p.name) + " " + (p.user.empty() ? std::string("<user>") : ps(p.user)) + " <password>\n";
        if (!p.serverBehindNat) {
            s += "\n# If the server is behind NAT (error 809), set PolicyAgent\\AssumeUDPEncapsulationContextOnSendRule = 2\n";
            s += "# (DWORD) under HKLM\\SYSTEM\\CurrentControlSet\\Services and reboot.\n";
        }

        return s;
    }

    /* Apple profile. */
    std::string AppleL2tpMobileConfig(const SL2tpClientProfile& p) {
        std::string vpnUuid = uuid();
        std::string profileUuid = uuid();
        std::string id = "org.libsbox.l2tp." + ident(p.server);
        std::string s;
        s += "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        s += "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n";
        s += "<plist version=\"1.0\">\n<dict>\n";
        s += "  <key>PayloadContent</key>\n  <array>\n    <dict>\n";
        s += "      <key>PayloadType</key><string>com.apple.vpn.managed</string>\n";
        s += "      <key>PayloadVersion</key><integer>1</integer>\n";
        s += "      <key>PayloadIdentifier</key><string>" + xml(id) + ".vpn</string>\n";
        s += "      <key>PayloadUUID</key><string>" + vpnUuid + "</string>\n";
        s += "      <key>PayloadDisplayName</key><string>" + xml(p.name) + "</string>\n";
        s += "      <key>UserDefinedName</key><string>" + xml(p.name) + "</string>\n";
        s += "      <key>VPNType</key><string>L2TP</string>\n";
        s += "      <key>PPP</key>\n      <dict>\n";
        s += "        <key>CommRemoteAddress</key><string>" + xml(p.server) + "</string>\n";
        if (!p.user.empty()) {
            s += "        <key>AuthName</key><string>" + xml(p.user) + "</string>\n";
        }

        if (!p.password.empty()) {
            s += "        <key>AuthPassword</key><string>" + xml(p.password) + "</string>\n";
        }

        s += "      </dict>\n";
        s += "      <key>IPSec</key>\n      <dict>\n";
        s += "        <key>AuthenticationMethod</key><string>SharedSecret</string>\n";
        s += "        <key>LocalIdentifierType</key><string>KeyID</string>\n";
        s += "        <key>SharedSecret</key><data>" + base64(p.psk) + "</data>\n";
        s += "      </dict>\n";
        s += "      <key>IPv4</key>\n      <dict>\n";
        s += "        <key>OverridePrimary</key><integer>" + std::string(p.routes.empty() ? "1" : "0") + "</integer>\n";
        s += "      </dict>\n";
        s += "    </dict>\n  </array>\n";
        s += "  <key>PayloadType</key><string>Configuration</string>\n";
        s += "  <key>PayloadVersion</key><integer>1</integer>\n";
        s += "  <key>PayloadIdentifier</key><string>" + xml(id) + "</string>\n";
        s += "  <key>PayloadUUID</key><string>" + profileUuid + "</string>\n";
        s += "  <key>PayloadDisplayName</key><string>" + xml(p.name) + "</string>\n";
        s += "  <key>PayloadOrganization</key><string>" + xml(p.organization) + "</string>\n";
        s += "</dict>\n</plist>\n";
        return s;
    }

    /* Android and manual Apple hints. */
    std::string AndroidL2tpSetup(const SL2tpClientProfile& p) {
        std::string s;
        s += "Android (built-in client, \"L2TP/IPSec PSK\"):\n";
        s += "  Settings > Network & internet > VPN > + (Add VPN)\n";
        s += "    Name:                  " + p.name + "\n";
        s += "    Type:                  L2TP/IPSec PSK\n";
        s += "    Server address:        " + p.server + "\n";
        s += "    L2TP secret:           (leave empty)\n";
        s += "    IPSec identifier:      (leave empty)\n";
        s += "    IPSec pre-shared key:  " + p.psk + "\n";
        s += "    Username / Password:   " + (p.user.empty() ? std::string("<your account>") : p.user) + "\n";
        if (!p.routes.empty()) {
            s += "    Forwarding routes:     ";
            for (size_t i = 0; i < p.routes.size(); ++i) {
                s += (i ? " " : "") + p.routes[i];
            }

            s += "  (Show advanced options)\n";
        }

        s += "  Note: Android 12 and later only keep L2TP/IPSec profiles created before the upgrade;\n";
        s += "  new devices need IKEv2 (sbox-ike) instead.\n\n";
        s += "macOS (System Settings > VPN > Add VPN Configuration > L2TP over IPSec) and iOS\n";
        s += "(Settings > General > VPN & Device Management > VPN > Add VPN Configuration > Type L2TP):\n";
        s += "    Server: " + p.server + ", Account: " + (p.user.empty() ? std::string("<your account>") : p.user) +
             ", Password, Shared secret / Secret: " + p.psk + "\n";
        s += "    Or install the .mobileconfig printed by `sbox-l2tp profile --format apple`.\n";
        return s;
    }

}
}
